spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootjpa
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true


# 静态资源配置
resources:
  static-locations: classpath:/static/

# Thymeleaf模板引擎配置
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
  cache: false